# Input
input:
  trait: "T2D"
  gwas_raw: "/opt/workflow/data/sharedata/GWAS_summary/01_Public/01_cojo/DIAMANTE_EUR_T2D_2022_NG.txt"
  gwas: "/opt/workflow/data/sharedata/GWAS_summary/01_Public/01_cojo/DIAMANTE_EUR_T2D_2022_NG.txt"
  output: "/opt/workflow/data/guoyazhou/GAMMA_git_data"

script:
  work_path: "/opt/workflow/data/guoyazhou/GAMMA_git/L2G/MAGIC"
  path: "/opt/workflow/data/guoyazhou/GAMMA_github/MAGIC/scripts"
  
software:
  smr: "/opt/workflow/data/yangwen/alpha-software/smr/smr-1.3.2-alpha7-linux"
  plink1_9: "/opt/workflow/data/guoyazhou/software/plink/plink1.90beta/plink_1.90_beta"
  plink2: "/opt/workflow/data/guoyazhou/software/plink/plink2.00alpha/plink2"
  
environment:
  R_421: "r"

reference:
  reference_bfile: "/opt/workflow/data/guoyazhou/data/Reference/UKB_Reference_genotype/genotype_10k_hg38/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38"
  reference_bld: "/opt/workflow/cache/smr/bld_format/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38_4Mb"
  reference_all_bim: "/opt/workflow/data/sharedata/LD_reference/UKB/genotype_10K/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38_chrALL.bim"

gene:
  gencode: "/opt/workflow/data/qiting/data/annotation/gencode/gencode.v40.GRCh38.gene.annotation.bed"

magic:
  QTL_list: "/opt/workflow/scripts/GAMMA_0.1.2/scripts/L2G/MAGIC_data/QTL_data/QTL_list.txt"
  QTL_name_list: "/opt/workflow/scripts/GAMMA_0.1.2/scripts/L2G/MAGIC_data/QTL_data/QTL_data_name_list.txt"
  R_functions: "/opt/workflow/scripts/GAMMA_0.1.2/scripts/L2G/magic_functions.r"
  CpG_link: "/opt/workflow/data/qiting/SMR_Cauchy/link/consensus3/CpG_consensus3.link"
  hQTL_link: "/opt/workflow/data/qiting/SMR_Cauchy/link/consensus3/hQTL_consensus3.link"
  caQTL_link: "/opt/workflow/data/qiting/SMR_Cauchy/link/consensus3/caQTL_consensus3.link"

smr:
  maf: 0.01
  peqtl_smr: 5.0e-8
  peqtl_heidi: 1.57e-3
  batch_num: 3

clumping:
  field: P
